### ISSUE TITLE
Wish: default to Node 4.3 environment

### ISSUE THREAD

**Issue by markstos** [u-minor/aglex#5]
Currently the Lambda is being set to run in the Node 0.10 environment. Setting the default to Node 4.3 would be preferred to take advantage of newer syntax.    Having a `runtime` config option in the YAML file could be useful.

**Comment by markstos** [comment]
Unrelated, I gave this module a positive review on my blog, here: http://mark.stosberg.com/blog/tech/review-of-nodejs-lambda-serverless/

**Comment by u-minor** [comment]
You can use `Runtime` param to set Node 4.3 in the yaml file.

https://github.com/u-minor/aglex/blob/master/lib/aglexLib.js#L450

```
lambda:
  Handler: lambda.handler
  Runtime: nodejs4.3
  MemorySize: 128
  Timeout: 60
  FunctionName: YOUR_LAMBDA_FUNCTION_NAME
  Description: YOUR_LAMBDA_DESCRIPTION
  RoleName: YOUR_LAMBDA_EXECUTION_ROLE # Role ARN will generate from RoleName automatically
```

I will update default params. 
Thanks!
